### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by ryanmclaughlin** [piotrkulpinski/chapman#2]
Attempting to run chapman to edit a Chipmunk theme I purchased, but getting this error:

```
⠋ Running chapman...
/Users/mack/.asdf/installs/nodejs/6.13.1/.npm/lib/node_modules/chapman/bin/chapman.js:37
      if (config.tasks.includes(task)) {
                      ^

TypeError: Cannot read property 'includes' of undefined
    at fs.readdirSync.forEach.file (/Users/mack/.asdf/installs/nodejs/6.13.1/.npm/lib/node_modules/chapman/bin/chapman.js:37:23)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/mack/.asdf/installs/nodejs/6.13.1/.npm/lib/node_modules/chapman/bin/chapman.js:34:31)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
```

**Comment by piotrkulpinski** [comment]
Hi @ryanmclaughlin 

Chipmunk theme was built on an older version of this tool, so you need to use v1.1.2 to be able to run it with the theme: 

`npm i -g chapman@1.1.2`

Hope that'll help with the issues.

/ Piotrek

**Comment by ryanmclaughlin** [comment]
@piotrkulpinski Thanks, definitely fixed it. I've got Browsersync running now, but when I go to `localhost:3000` it seems to just hang and never loads. Any ideas?

**Comment by piotrkulpinski** [comment]
@ryanmclaughlin Looks like you have some issues with your local environment. This is a common problem so try googling it.

**Comment by ryanmclaughlin** [comment]
@piotrkulpinski thanks. attempted that, but not sure what's going on.

Can I just manually compile the `.scss` files? Is the `.twig` template site integrated at all with the actual wordpress files/theme or is it a standalone `styleguide` if you will, meaning if I update the `php` files I need to update the `twig` template as well to maintain it?

**Comment by piotrkulpinski** [comment]
@ryanmclaughlin If you just want to modify styles, manually compiling `.scss` will be enough. As for the templates, PHP files are for WordPress, and Twig files are just static files used for generating static HTML which is used for our standalone HTML package.
